### ISSUE TITLE
Add CSV as database for Telegram Bot

### ISSUE THREAD

**Issue by abhi3700** [python-botogram/botogram#141]
I want to add CSV file as database for my telegram Bot.

I am adding this as:
```py
bot = botogram.create(API_key)
bot.about = "This is a Key Provider Bot. \nThis provides keys (max. 2 per day) to a user based on information - username, location"
bot.owner = "@abhi3700"
# -------------------------------------------------------Redis DB---------------------------------------
# define Redis database
r = redis.from_url(REDIS_URL)

# -------------------------------------------------------'phone' global var------------------------------------------------------------------------
phone_global = "DUMMY"      # replace with "" string in production release

# -------------------------------------------------------Excel CSV dataframes--------------------------
df_a = pd.read_csv('../keys/A.csv')
df_b = pd.read_csv('../keys/B.csv')
df_c = pd.read_csv('../keys/C.csv')
df_d = pd.read_csv('../keys/D.csv')
df_e = pd.read_csv('../keys/E.csv')

.....
.....
.....
# ================================================MAIN==========
if __name__ == "__main__":
    bot.run()
```

__Terminal:__
```console
$ python app/bot.py
Traceback (most recent call last):
  File "app/bot.py", line 22, in <module>
    df_a = pd.read_csv('../keys/A.csv')
  File "F:\Softwares\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "F:\Softwares\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "F:\Softwares\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "F:\Softwares\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "F:\Softwares\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'../keys/A.csv' does not exist: b'../keys/A.csv'
```

I don't why it is like this....

I read it somewhere that in this case, one can upload CSV to postgreSQL database.

Is it correct? If yes, then how, please guide.

**Comment by MarcoBuster** [comment]
This is not a botogram related issue.
